curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "National Science Center 1", "type": "NCN", "activity": "Funding research projects" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "European Research Fund 2", "type": "EU", "activity": "Supporting collaborative research" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Polish National Center 3", "type": "NCBR", "activity": "Innovation grants" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Future Research Institute 4", "type": "FNP", "activity": "Scientific programs" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Global Science Fund 5", "type": "EU", "activity": "International research funding" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Innovation Support Agency 6", "type": "NCBR", "activity": "Startup grants" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "National Research Council 7", "type": "NCN", "activity": "Basic research funding" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "European Science Board 8", "type": "EU", "activity": "Scientific collaboration" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Polish Innovation Fund 9", "type": "NCBR", "activity": "Applied research grants" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Future Knowledge Center 10", "type": "FNP", "activity": "Research fellowships" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Science and Tech Fund 11", "type": "EU", "activity": "Technology research grants" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "National Innovation Council 12", "type": "NCN", "activity": "Innovation research" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Polish Science Fund 13", "type": "NCBR", "activity": "Science and technology projects" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "European Knowledge Fund 14", "type": "EU", "activity": "Cross-border research" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Future Science Foundation 15", "type": "FNP", "activity": "Research grants" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Innovation Research Center 16", "type": "NCBR", "activity": "Innovation funding" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "National Research Initiative 17", "type": "NCN", "activity": "Basic and applied research" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "European Science Council 18", "type": "EU", "activity": "Research programs" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Polish Future Fund 19", "type": "FNP", "activity": "Scientific advancement" }}'
curl -X POST http://localhost:8080/api/agencies -H "Content-Type: application/json" -d '{ "entity": { "name": "Global Innovation Agency 20", "type": "EU", "activity": "Funding science projects" }}'
